name = "erdos"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Erdos"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.31.0"

[[lean_lib]]
name = "Erdos"
